steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_SERVICE_NAME}:$SHORT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_SERVICE_NAME}:$SHORT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_SERVICE_NAME}:$SHORT_SHA'
      - '--region'
      - '${_REGION}'
      - '--project'
      - '${_PROJECT_ID}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--vpc-connector=hello-connector'
      - '--vpc-egress=all-traffic'
      - '--update-secrets=KEYCLOAK_URL=KEYCLOAK_URL:latest,REALM=REALM:latest,CLIENT_ID=CLIENT_ID:latest,CLIENT_SECRET=CLIENT_SECRET:latest,API_BASE_URL=API_BASE_URL:latest'

substitutions:
  _REGION: 'europe-west1'
  _PROJECT_ID: 'hello-490012'
  _SERVICE_NAME: 'hello-symphony'
  _REPO: 'hello-symphony'

options:
  logging: CLOUD_LOGGING_ONLY
